import { Container, Header } from "@/styles/styles";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import { SiThemoviedatabase } from "react-icons/si";
import { TfiBackLeft } from "react-icons/tfi";

export default function Busca() {
  const [searchText, setSearchText] = useState("");
  const [movies, setMovies] = useState([]);

  const handleSearch = async () => {
    if (searchText !== "") {
      const result = await fetch(
        `http://localhost:3000/api/search?q=${searchText}`
      );
      const json = await result.json();

      return setMovies(json.list);
    }
  };
  return (
    <>
      <Head>
        <title>NEXT MOVIES</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>
        <h2>
          NEXT MOVIES <SiThemoviedatabase />
        </h2>
        <Link href="/">
          Voltar <TfiBackLeft />
        </Link>
      </Header>
      <Container>
        <h1>Busca</h1>
        <div className="input-area">
          <input
            type="text"
            value={searchText}
            onChange={(e) => setSearchText(e.target.value)}
            placeholder="Digite aqui o nome do filme..."
          />
          <button onClick={handleSearch}>Buscar</button>
        </div>

        <ul>
          {movies.map(
            (e: any, i: number) =>
              e.poster_path !== null && (
                <li key={i}>
                  <a href={`/movie/${e.id}`}>
                    <img
                      src={`https://image.tmdb.org/t/p/original${e.poster_path}`}
                      width="250"
                      height="300"
                      alt="e.title"
                      className="main-image"
                    />
                    {e.title}
                  </a>
                </li>
              )
          )}
        </ul>
      </Container>
    </>
  );
}
