import { Container, Header } from "@/styles/styles";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import { SiThemoviedatabase } from "react-icons/si";
import { BiSearchAlt } from "react-icons/bi";

interface IPropsHome {
  list: any;
}

export default function Home({ list }: IPropsHome) {
  return (
    <>
      <Head>
        <title>NEXT MOVIES</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>
        <h2>
          NEXT MOVIES <SiThemoviedatabase />
        </h2>
        <Link href="/busca">
          Ir para a busca <BiSearchAlt />
        </Link>
      </Header>
      <Container>
        <h1>Filmes em Destaque</h1>

        <ul>
          {list.map((e: any, i: number) => (
            <li key={i}>
              <a href={`/movie/${e.id}`}>
                <img
                  src={`https://image.tmdb.org/t/p/original${e.poster_path}`}
                  width="250"
                  height="300"
                  alt="e.title"
                  className="main-image"
                />
                {i + 1}. {e.title}
              </a>
            </li>
          ))}
        </ul>
      </Container>
    </>
  );
}

export async function getServerSideProps() {
  const res = await fetch("http://localhost:3000/api/trending");
  const json = await res.json();
  return {
    props: {
      list: json.list,
    },
  };
}
