import Head from "next/head";
import Link from "next/link";
import { SiThemoviedatabase } from "react-icons/si";
import { TfiBackLeft } from "react-icons/tfi";
import { Container, Header } from "../../styles/styles";

interface IPropsMovieItem {
  info: any;
}

export default function MovieItem({ info }: IPropsMovieItem) {
  return (
    <>
      <Head>
        <title>NEXT MOVIES</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>
        <h2>
          NEXT MOVIES <SiThemoviedatabase />
        </h2>
        <Link href="/">
          Voltar <TfiBackLeft />
        </Link>
      </Header>
      <Container>
        <h1>
          Filme: <span>{info.title}</span>
        </h1>
        <span className="overview">{info.overview}</span>
        <p className="rating">
          Avaliação: {parseInt(info.vote_average).toFixed(1)}
        </p>
        <img src={`https://image.tmdb.org/t/p/original${info.backdrop_path}`} />
      </Container>
    </>
  );
}

export async function getServerSideProps(context: any) {
  const res = await fetch(
    `http://localhost:3000/api/movie/${context.params.id}`
  );
  const json = await res.json();
  return {
    props: {
      info: json.info,
    },
  };
}
